server:
  port: 8080
spring:
  application:
    name: sharding-hdbc-demo
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yh.entity
